### ISSUE TITLE
Nil pointer dereference panic in go/ir/create.go:54

### ISSUE THREAD

**Issue by Alfus** [dominikh/go-tools#1500] opened 2024-02-27 20:32 UTC
I get the following error when the go vscode extension runs staticcheck:
```
2024-02-27 15:26:18.038 [error] Error while running tool: /Users/alfred/go/bin/staticcheck
2024-02-27 15:26:18.038 [error] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x100b6326c]

goroutine 440 [running]:
honnef.co/go/tools/go/ir.memberFromObject(0x1400058abd0, {0x0, 0x0?}, {0x0?, 0x0})
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:54 +0x3c
honnef.co/go/tools/go/ir.membersFromDecl(0x1400058abd0, {0x100e356d8?, 0x140008161c0?})
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:155 +0x29c
honnef.co/go/tools/go/ir.(*Program).CreatePackage(0x1400181e1c0, 0x14000cdefc0, {0x140004baff0, 0xa, 0xa}, 0x140004bb090, 0x0)
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:207 +0x76c
honnef.co/go/tools/internal/passes/buildir.run(0x1400042d380)
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/internal/passes/buildir/buildir.go:85 +0x108
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x140018345a0, {0x100e37068?, 0x140018360a0})
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:992 +0x61c
honnef.co/go/tools/lintcmd/runner.genericHandle({0x100e37068?, 0x140018360a0}, {0x100e37068?, 0x14001836000?}, 0x0?, 0x140003e35e0, 0x14001826940)
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x11c
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers in goroutine 348
	/Users/alfred/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1061 +0x590
```

The output of 'staticcheck -debug.version':
```
staticcheck 2023.1.7 (v0.4.7)

Compiled with Go version: go1.21.4
Main module:
        honnef.co/go/tools@v0.4.7 (sum: h1:9MDAWxMoSnB6QoSqiVr7P5mtkT9pOc1kSxchzPCnqJs=)
Dependencies:
        github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
        golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
        golang.org/x/mod@v0.12.0 (sum: h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=)
        golang.org/x/sys@v0.11.0 (sum: h1:eG7RXZHdqOJ1i+0lgLgCpSXAp6M3LYlAo6osgSi0xOM=)
        golang.org/x/tools@v0.12.1-0.20230825192346-2191a27a6dc5 (sum: h1:Vk4mysSz+GqQK2eqgWbo4zEO89wkeAjJiFIr9bpqa8k=)
```

The output of 'go version': `go version go1.22.0 darwin/arm64`
 The output of 'go env':
```
go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/alfred/Library/Caches/go-build'
GOENV='/Users/alfred/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/alfred/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/alfred/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/alfred/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.darwin-arm64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/alfred/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.darwin-arm64/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/alfred/dev/kafka-gateway/go.mod'
GOWORK='/Users/alfred/dev/kafka-gateway/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/5p/4y6d0zbd0y74ff9w7gy367gc0000gn/T/go-build28875726=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by Alfus** [comment] 2024-02-28 14:39
I ended up just reverting to 1.21.7, thanks for the info! (1.22 seems to have broken a lot of things)

**Comment by Akaame** [comment] 2024-02-28 19:03
Someone and I are also having a similar problem here: https://github.com/dominikh/go-tools/issues/1496#issuecomment-1961202394

My solution was to simply recompiling `staticcheck` with 1.22.

**Comment by Akaame** [comment] 2024-02-29 11:04
I think I actually reproduced something similar but not exactly sure it is exactly the same

`podman run -it --rm golang:1.22`

Then in the container

```
git clone https://github.com/dominikh/go-tools.git
wget -c https://go.dev/dl/go1.21.7.linux-arm64.tar.gz
wget -c https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
rm -rf /usr/local/go
tar -C /usr/local/ -xzf go1.21.7.linux-arm64.tar.gz
go install honnef.co/go/tools/cmd/staticcheck@v0.4.6
go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
rm -rf /usr/local/go
tar -C /usr/local/ -xzf go1.22.0.linux-arm64.tar.gz
cd go-tools/
staticcheck ./...
```

I get this

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2e1fbc]

goroutine 137 [running]:
honnef.co/go/tools/go/ir.memberFromObject(0x4000463710, {0x0, 0x0?}, {0x0?, 0x0})
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:54 +0x3c
honnef.co/go/tools/go/ir.membersFromDecl(0x4000463710, {0x5b9828?, 0x400362cf40?})
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:137 +0x378
honnef.co/go/tools/go/ir.(*Program).CreatePackage(0x4008953dc0, 0x4001aa59e0, {0x4004383208, 0x1, 0x1}, 0x40068bba40, 0x0)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/create.go:207 +0x76c
honnef.co/go/tools/internal/passes/buildir.run(0x4000dabc70)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/internal/passes/buildir/buildir.go:85 +0x108
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x4003a5d4d0, {0x5bb1e8?, 0x4008a39ae0})
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:992 +0x61c
honnef.co/go/tools/lintcmd/runner.genericHandle({0x5bb1e8?, 0x4008a39ae0}, {0x5bb1e8?, 0x4008a399a0?}, 0x476740?, 0x0, 0x4000e03030)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x11c
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0x4000dbfbd0, 0x4000d58c60, 0x40068bb9f0)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1065 +0x5c8
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x4?, 0x4000d58c60)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:720 +0x160
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0x4000dbfbd0, {0x5bb230?, 0x4000d58c60})
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:577 +0x700
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x5bb230?, 0x4000d58c60?})
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1268 +0x34
honnef.co/go/tools/lintcmd/runner.genericHandle({0x5bb230?, 0x4000d58c60}, {0x5bb230?, 0x4000cc3680?}, 0x0?, 0x400024e740, 0x40062b7ec0)
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x11c
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run in goroutine 1
	/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1267 +0x498
```

**Comment by Akaame** [comment] 2024-02-29 11:10
Or `podman run -it --rm golang:1.21`

Then

```
go install honnef.co/go/tools/cmd/staticcheck@v0.4.6
go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
wget -c https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
git clone https://github.com/dominikh/go-tools.git
rm -rf /usr/local/go
tar -C /usr/local/ -xzf go1.22.0.linux-arm64.tar.gz
cd go-tools/
staticcheck ./...
```

Again with the same error.

This all is traced back to doing `go install honnef.co/go/tools/cmd/staticcheck@v0.4.7` while your Go version is still `1.21`. If you execute `go install honnef.co/go/tools/cmd/staticcheck@v0.4.7` after switching back to Go `1.22` again. The problem goes away. But, I know I am already in the wrong because I tried installing staticcheck v0.4.7 with Go 1.21.

**Comment by dominikh** [comment] 2024-02-29 18:20
Yes, for Staticcheck to be able to process Go 1.22 source code, it has to be compiled with Go 1.22. Merely running with Go 1.22 on your path after having bult Staticcheck with 1.21 is not sufficient.

Since @Alfus built with Go 1.21 I will assume that that is the cause of this issue and will close the issue.

I think that in the future, we'll try to detect such version mismatches and outright refuse to process Go code that is too new.

**Comment by dominikh** [comment] 2024-02-29 18:20
Also thank you @Akaame for digging into this.

**Closed by dominikh** 2024-02-29 18:20 UTC

**Comment by Alfus** [comment] 2024-02-29 18:46
My underlying issue was, while my repo was 1.22.0, my homebrew install was 1.21.4, and that is what vscode was using to compile the tools. I am now on 1.22.0 everywhere, and everything is working, thanks!
