### ISSUE TITLE
Duplicate output messages

### ISSUE THREAD

**Issue by mnarrell** [dominikh/go-tools#480] opened 2019-05-17 21:28 UTC
I've created a compile time issue and run `staticcheck` over that package.  I see the following:

```
$ staticcheck ./...
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
model.go:127:36: invalid operation: cannot indirect cifOrigin (variable of type string) (compile)
```

I'm not sure why this error is duplicated.

**Comment by dominikh** [comment] 2019-05-17 23:38
@mnarrell can you retry with the `incr` branch of staticcheck? 

```
cd $GOPATH/src/honnef.co/go/tools
git checkout incr
go install ./cmd/staticcheck
```

**Comment by mnarrell** [comment] 2019-05-18 14:55
Unfortunately no.  Here's the output, but I had to redact some of the package names

```
$ staticcheck ./...
-: could not analyze dependency ... of ... :
        could not run config@..., preventing 2 analyzers from running: error loading staticcheck.conf: Near line 0 (last key parsed ''): bare keys cannot contain '/' (compile)
-: could not analyze dependency ... of .../decision.test (compile)
-: could not analyze dependency .../test of .../decision_test [.../decision.test]:
        could not analyze ... of .../test:
        could not run config..., preventing 2 analyzers from running: error loading staticcheck.conf: Near line 0 (last key parsed ''): bare keys cannot contain '/' (compile)
```

**Comment by mnarrell** [comment] 2019-05-18 14:57
Here's the output without forced errors:

```
$ staticcheck ./...
-: could not run config@.../config, preventing 114 analyzers from running: error loading staticcheck.conf: Near line 0 (last key parsed ''): bare keys cannot contain '/' (compile)
```

**Comment by dominikh** [comment] 2019-05-18 22:55
The initial bug report was about compilation errors, but your followup comment is about invalid config files. Those aren't the same thing.

However, if you can't reproduce the issue, then that is not an "unfortunately no" but a "luckily no". The incr branch will eventually be merged back into master, meaning the bug will be fixed in the next release.

**Comment by mnarrell** [comment] 2019-05-19 00:18
You should add to your release notes that `/* */` comments are no longer supported.

**Closed** 2019-05-19 00:18 UTC
Labels: waiting-for-feedback
