### ISSUE TITLE
unused: mistakenly flags fields in an anonymous struct

### ISSUE THREAD

**Issue by y0ssar1an** [dominikh/go-tools#262] opened 2018-02-19 18:59 UTC
I encountered this while running `unused` on [`rs/zerolog`](https://github.com/rs/zerolog).
```sh
% unused ./...
log_test.go:371:3: field l is unused (U1000)
log_test.go:372:3: field p is unused (U1000)
```
Here is [the offending code](https://github.com/rs/zerolog/blob/9ee98f91c4e05af131b20fe79acdade85dca08fe/log_test.go#L371-L372).
```go
type levelWriter struct {
	ops []struct {
		l Level
		p string
	}
}
```
...but it appears to be used [right below](https://github.com/rs/zerolog/blob/9ee98f91c4e05af131b20fe79acdade85dca08fe/log_test.go#L381-L384).
```go
func (lw *levelWriter) WriteLevel(lvl Level, p []byte) (int, error) {
	lw.ops = append(lw.ops, struct {
		l Level
		p string
	}{lvl, string(p)})
	return len(p), nil
}
```
Is `unused` confused by the anonymous struct?

### Version
I'm using [the latest master commit](https://github.com/dominikh/go-tools/commit/8ed405e85c65fb38745a8eafe01ee9590523f172) (Feb 19, 2018), built with Go 1.10.

**Comment by dominikh** [comment] 2018-02-19 22:13
It is not used "right below". Merely assigning to the fields does not count as usage if the fields are never being read (either directly, or indirectly via reflection.)

You are right that they *are* being used, however, via reflect.DeepEqual. I will have to check if this bug is caused by the use of DeepEqual, or by the use of anonymous structs.

**Comment by dominikh** [comment] 2018-02-19 22:14
https://github.com/dominikh/go-tools/issues/203 would suggest that we are struggling with anonymous types, though. Which isn't surprising; unused is due for a redesign and rewrite.

**Comment by dominikh** [comment] 2019-04-10 12:45
This should be fixed in master.

**Closed by dominikh** 2019-04-10 12:45 UTC
Labels: false-positive, started
