### ISSUE TITLE
Unused: False negative for cases where variable is checked only to set itself

### ISSUE THREAD

**Issue by viswajithiii** [dominikh/go-tools#764] opened 2020-05-29 06:13 UTC
Consider the following code:
```go

func returnsString() string {
   // returns some string
}

func myFunc() {
  a := returnsString()
  if a == "UNSET" {
      a = ""
  }
  return returnsString() // Intended to use `a`, but did not!
}
```

`a` is an unused variable here -- even though its value is checked, the value is used _only_ to do something to `a`. However, U1000 does not catch this.

This is a tricky one, since if the code in the branch does literally anything other than assigning to `a`, then the `if a == "UNSET"` check of `a` _is_ an actual use of `a`. It _was_ an actual bug I found in my code, though!

**Comment by dominikh** [comment] 2020-06-01 10:54
This is not the responsibility of U1000, but of SA4006. And this seems to be a duplicate of #191. In particular, note that we already flag the following code:

```
package pkg

func returnsString() string {
	// returns some string
	return ""
}

func otherFn() string { return "" }

func myFunc() string {
	a := returnsString()
	if a == "UNSET" {
		a = otherFn()
	}
	return returnsString() // Intended to use `a`, but did not!
}
```

```
$ staticcheck -checks SA4006
../../../../../sandbox/foo/foo.go:13:3: this value of a is never used (SA4006)
```

I will close this issue as a duplicate of #191.

**Closed by dominikh** 2020-06-01 10:54 UTC
Labels: false-negative
