### ISSUE TITLE
Flow analysis yields confusing false positive with U1000; -matrix doesn't help

### ISSUE THREAD

**Issue by cespare** [dominikh/go-tools#1244] opened 2022-04-06 20:03 UTC
I'm using 2022.1.

This is pretty similar to #633. (It also has a surface similarity to #48 but it's more or less unrelated.)

We encountered a staticcheck false positive with code like this:

```
-- main.go --
package main

func main() {
       foo()
       bar()
}
-- main_linux.go --
package main

import "fmt"

func foo() {
       fmt.Println("do something linux-specific")
}

func bar() {
       fmt.Println("do something else linux-specific")
}
-- main_other.go --
//go:build !linux

package main

func foo() {
       panic("unimplemented")
}

func bar() {
       panic("unimplemented")
}
```

(Or see demo in github [here](https://github.com/cespare/misc/tree/main/u1000panic).)

We have a tool that is essentially linux-specific, but we want to be able to compile and test it as much as possible on other OSes as well. So the linux-specific functions are factored out into a file guarded by a build tag, and those functions also exist in a `!linux` file where they simply panic. Then at least this can compile on macOS and we can run the tests (as long as they don't exercise those functions -- if they do, those tasks can use `t.Skip`).

Here's the result:

```
$ GOOS=linux staticcheck .
$ GOOS=darwin staticcheck .
main_other.go:9:6: func bar is unused (U1000)
```

I understand why this is happening, and I believe it's all working as intended:

* With `GOOS=darwin` staticcheck only considers `main.go` and `main_other.go`
* Since `foo` unconditionally panics, staticcheck knows that `main` cannot proceed to `bar()`
* Therefore, `bar` is "unused"

However, in context, this is an unintuitive and unhelpful result.

If staticcheck has analyzed `main` and realized that everything after `foo()` is unreachable, it would be much easier for the user to understand if staticcheck reported that as "code after this point is unreachable" rather than silently establishing that fact and then using it to infer the unused-ness of the functions. The user has to see the U1000 error and then reverse that inference in order to understand the problem that staticcheck is seeing.

This problem is very similar to the ones described [on the build tags documentation page](https://staticcheck.io/docs/running-staticcheck/cli/build-tags/) and so I had hoped that I could work around this by merging results/using `-matrix`. However, that doesn't work:

```
$ staticcheck -matrix . <<EOF
linux: GOOS=linux
macos: GOOS=darwin
EOF
main_other.go:9:6: func bar is unused [macos] (U1000)
```

Maybe that's because the "unused" `bar` is different from the used `bar`?

**Comment by dominikh** [comment] 2022-04-07 14:32
> Maybe that's because the "unused" bar is different from the used bar?

Correct. Merging happens on a per-diagnostic basis and depends on file names and locations. The two functions named `bar` aren't related, as far as the merging is concerned.

I don't have much else to say here. You're right that the current behavior isn't good. Unfortunately, it's not a conscious decision, and changing it isn't trivial. It's the result of implementing `U1000` on top of the IR, which takes control flow into consideration (which benefits most checks). 

A dirty workaround would be to construct a separate IR for U1000 and make it dumber, but that would have an unwelcome effect on runtime and memory usage. The proper, long-term solution is to rewrite U1000 to operate on the AST instead. If the code, as written, references an identifier, then it is used, regardless of actual runtime behavior/impossible control flow. As you can imagine, such a rewrite is labor intensive. It is, however, on my to-do list. 

I will close this as a duplicate of #633 – your example is virtually identical to it, except that you've called it `foo`, not `Skip`. I do intend to fix this sooner than later.

**Closed by dominikh** 2022-04-07 14:32 UTC
Labels: false-positive, needs-triage
