### ISSUE TITLE
advise against modifying package global errors in non-main packages

### ISSUE THREAD

**Issue by soypat** [dominikh/go-tools#1418] opened 2023-07-02 00:23 UTC
```go
package mylib

import "io"

func DoWork() {
    io.EOF = nil // Don't assign to package global errors.
    io.EOF = errors.New("out of memory") // OK, now you're just being malicious.
    io.EOF = errors.New("EOF") // Stop. Please.
}
```

**Comment by dominikh** [comment] 2023-07-02 03:11
Duplicate of #1152.

**Closed by dominikh** 2023-07-02 03:11 UTC
Labels: needs-triage
