### ISSUE TITLE
Suggest combining multiple appends into one

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#923] opened 2021-02-01 12:02 UTC
This was brought up in fyne-io/fyne#1888 as a fix from deepsource. I thought it would be better to add this change to staticcheck instead.

The idea is that multiple short appends right after each other should be added into one append call instead. This should be faster than appending to the slice multiple times right after each other.

Before:
```go
contents = append(contents, newColorBasicPicker(p.selectColor))
contents = append(contents, newColorGreyscalePicker(p.selectColor))
```

After:
```go
contents = append(contents, newColorBasicPicker(p.selectColor), newColorGreyscalePicker(p.selectColor))
```

**Comment by dominikh** [comment] 2021-02-01 12:34
I'm unsure if we can add this to `simple`, or if it has to be relegated to `quickfix`. I am concerned that this is too opinionated a suggestion. In code that isn't performance critical, is

```
x = append(x, somethingLong)
x = append(x, somethingLong)
x = append(x, somethingLong)
x = append(x, somethingLong)
```

objectively worse than

```
x = append(x, somethingLong
    somethingLong,
    somethingLong
    somethingLong)
```
?

**Comment by Jacalz** [comment] 2021-02-01 12:45
I’s say that it largely depends on the length of the items added into one append. It might make sense for shorter items, but not not for very long items. As for if it is objectively worse, I think the first one has a lot of repetitive code so the second one might be more easy to read, especially if the first occurrence of `somethingLong` is on a new line.

**Comment by dominikh** [comment] 2021-02-01 12:58
> I’s say that it largely depends on the length of the items added into one append

I agree, but that makes the check even more subjective, as different people will have different opinions on desired line lengths.

I've checked Go's source code, and they don't seem averse to using multiple appends whatsoever: https://play.golang.org/p/zn38rEViRaY (found via `rg -n --pcre2 -U '(.+?) = append\(\1, .+\n\s*\1 = append\(\1, '` in GOROOT/src).

**Comment by dominikh** [comment] 2021-02-01 13:00
From a performance point of view, I am surprised that the Go compiler doesn't merge multiple appends into one.

**Comment by dominikh** [comment] 2021-02-01 16:33
Actually, this is a duplicate of #772.

**Closed by dominikh** 2021-02-01 16:33 UTC
Labels: needs-decision, new-check
