### ISSUE TITLE
Checker for defered functions that return a function

### ISSUE THREAD

**Issue by arp242** [dominikh/go-tools#767] opened 2020-05-31 21:19 UTC
The below code will print nothing since f() returns a function, you need to use `defer f()()` if you want it to actually run it. I think it would be useful to add a linter for this, since you practically never not want to run the returned function.

```
func main() {
    defer f()
}

func f() func() {
    return func() { fmt.Println("x") }
}
```

The Go compiler already refuses to compile just `defer f`, so perhaps it might be better to expand that check instead of adding one to staticcheck?

**Comment by arp242** [comment] 2020-05-31 22:13
Added a basic implementation here: https://github.com/zgoat/goatcounter/commit/45a63f005c35088deb2ac28a7dca24ad64be1200#diff-a5bff9fc0a1ecd49d6c47a6a7a12b468

This would have prevented a [serious bug](https://github.com/zgoat/goatcounter/commit/ece65ce) at least in one case btw, which unfortunately wasn't covered by the integration tests :-(

**Comment by dominikh** [comment] 2020-06-01 10:46
Closing as a duplicate of #466.

> The Go compiler already refuses to compile just defer f, so perhaps it might be better to expand that check instead of adding one to staticcheck?

The compiler can't refuse to compile this code. `f` might do other meaningful work, and the language specification doesn't forbid defers of functions that return functions.

**Closed by dominikh** 2020-06-01 10:46 UTC
Labels: needs-triage
