### ISSUE TITLE
Detect wrapped functions that can be passed directly

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#927] opened 2021-02-07 17:11 UTC
I have time and time again run into this in my own code and decided that it was worth opening a request for. The issue stems from using APIs that allow a function to be passed. I will usually wrap these functions like so out of pure habit:
```go
d.leftButton.OnTapped = func() {
	onClose()
}
```

When I should instead be able to more elegantly just do this (assuming that both functions have the same input and output parameters):
```
d.leftButton.OnTapped = onClose
```

This of course only works if the function contains one and only one function call. I don't know how smart the compiler is, but I would assume that the first one has the call overhead of two function calls and the lower one would be faster as it is passing the function pointer (I think).

**Comment by dominikh** [comment] 2021-02-07 17:26
I would hope that the compiler is smart enough to optimize this away, but IMO we should still flag this code, as it can be simplified and made easier to read. In fact, this is a duplicate of #123, so I am going to close this issue.

P.S. I hope me closing your duplicates isn't disheartening. Please keep these issues coming, I don't mind sorting through duplicates terribly much, and it's a good signal of what checks are worth prioritizing.

**Closed by dominikh** 2021-02-07 17:26 UTC
Labels: needs-triage

**Comment by Jacalz** [comment] 2021-02-07 18:42
No worries. I mostly blame myself for not finding that one when searching for issues 🙂
