### ISSUE TITLE
unused: false positive for methods in a interface defined inline

### ISSUE THREAD

**Issue by dolmen** [dominikh/go-tools#203] opened 2017-10-24 09:25 UTC
Real code from https://github.com/dolmen-go/flagx/blob/master/text.go
`unused` incorrectly reports `MarshalText`and `UnmarshalText` as unused functions.

```
type textValue struct {
	value interface {
		// encoding.TextMarshaler
		MarshalText() (text []byte, err error)
		// encoding.TextUnmarshaler
		UnmarshalText(text []byte) error
	}
}

func Text(v interface {
	// encoding.TextMarshaler
	MarshalText() (text []byte, err error)
	// encoding.TextUnmarshaler
	UnmarshalText(text []byte) error
}) Value {
	return &textValue{v}
}
```

**Comment by dominikh** [comment] 2017-10-24 09:30
This is probably a bug caused by the use of anonymous interfaces. Will be fixed once unused gets rewritten.

**Comment by tamird** [comment] 2017-11-20 13:10
There's a similar bug with anonymous structs, see https://github.com/golang/protobuf/pull/313/files#diff-835a1f89169d6f77d0471a7852c18fa4R171

**Comment by mrwonko** [comment] 2019-01-24 10:21
Another test case that doesn't involve structs:
```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	var argument interface {
		String() string // incorrectly marked as unused
	} = new(strings.Builder) // assignment optional for repro, but prevents panic
	f(argument)
}

func f(argument fmt.Stringer) {
	fmt.Println(argument.String())
}
```

**Comment by dolmen** [comment] 2019-02-15 08:44
The similar code to the one above by @mrwonko that uses a named interface doesn't raise the false positive:
```go
package main

import (
        "fmt"
        "strings"
)

func main() {
        var argument fmt.Stringer = new(strings.Builder) // assignment optional for repro, but prevents panic
        f(argument)
}

func f(argument fmt.Stringer) {
        fmt.Println(argument.String())
}
```

**Comment by dominikh** [comment] 2019-04-10 12:46
This should be fixed in master.

**Closed by dominikh** 2019-04-10 12:46 UTC
Labels: false-positive, started
