### ISSUE TITLE
False positive U1000 when a test is skipped

### ISSUE THREAD

**Issue by marten-seemann** [dominikh/go-tools#968] opened 2021-04-20 16:22 UTC
```go
func TestSkipping(t *testing.T) {
	t.Skip("skipping test")
	foo()
}

func foo() string {
	return "bar"
}
```

complains that `foo` is unused: `func foo is unused (U1000)`

**Comment by mvdan** [comment] 2021-04-20 16:41
Maybe staticcheck considers `testing.T.Skip` to be a terminal statement like `return` or `panic`, and then marks the rest of the body as dead code.

That's technically true, but I think I agree with Marten - skipping a flaky test temporarily is pretty common, and one shouldn't have to delete its code or add "nolint" directives.

**Comment by dominikh** [comment] 2021-04-25 09:33
> Maybe staticcheck considers testing.T.Skip to be a terminal statement like return or panic, and then marks the rest of the body as dead code.

Correct.

> or add "nolint" directives

Come again, what directives? :whelmed:

I'm aware of this problem, and it's on my todo list. I am going to close this as a duplicate of #633.

**Closed by dominikh** 2021-04-25 09:33 UTC
Labels: false-positive, needs-triage
