### ISSUE TITLE
"staticcheck ." on a new project gives: invalid Go version: "1.21.0"

### ISSUE THREAD

**Issue by mark-summerfield** [dominikh/go-tools#1433] opened 2023-08-13 10:56 UTC
- The output of 'staticcheck -version'
staticcheck 2023.1.3 (v0.4.3)

- The output of 'staticcheck -debug.version' (it is fine if this command fails)
staticcheck 2023.1.3 (v0.4.3)

Compiled with Go version: go1.21.0
Main module:
	honnef.co/go/tools@v0.4.3 (sum: h1:o/n5/K5gXqk8Gozvs2cnL0F2S1/g1vcGCAx2vETjITw=)
Dependencies:
	github.com/BurntSushi/toml@v1.2.1 (sum: h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=)
	golang.org/x/exp/typeparams@v0.0.0-20221208152030-732eee02a75a (sum: h1:Jw5wfR+h9mnIYH+OtGT2im5wV1YGGDora5vTv/aa5bE=)
	golang.org/x/mod@v0.7.0 (sum: h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=)
	golang.org/x/sys@v0.3.0 (sum: h1:w8ZOecv6NaNa/zC8944JTU3vz4u6Lagfk4RPQxv92NQ=)
	golang.org/x/tools@v0.4.1-0.20221208213631-3f74d914ae6d (sum: h1:9ZNWAi4CYhNv60mXGgAncgq7SGc5qa7C8VZV8Tg7Ggs=)
- The output of 'go version'
- The output of 'go env'
- Exactly which command you ran
staticcheck .

- Output of the command and what's wrong with the output
Output was:
invalid Go version: "1.21.0"

- Where we can read the code you're running Staticcheck on
On a simple helloworld.go.

**Comment by creachadair** [comment] 2023-08-13 23:46
I've also encountered this. Until a new release is tagged, you can work around it by pinning staticcheck to a newer commit (e.g., cee67be appears to work fine with all the cases I've tried so far).

**Comment by bconway** [comment] 2023-08-15 14:43
See also:

https://github.com/dominikh/go-tools/issues/1431

https://github.com/dominikh/go-tools/commit/ac367e4ba163000c50eb37da3a937471d42912ad

**Comment by dominikh** [comment] 2023-08-17 11:09
Closing as duplicate of #1431

**Closed by dominikh** 2023-08-17 11:09 UTC
Labels: false-positive, needs-triage
