### ISSUE TITLE
unused: global variable is treated as unused

### ISSUE THREAD

**Issue by Jacalz** [dominikh/go-tools#823] opened 2020-09-12 15:28 UTC
- The output of 'staticcheck -version':
`staticcheck 2020.1.5`
- The output of 'staticcheck -debug.version' (it is fine if this command fails)
```
staticcheck 2020.1.5

Compiled with Go version: go1.14.4
Main module:
	honnef.co/go/tools@v0.0.1-2020.1.5 (sum: h1:nI5egYTGJakVyOryqLs1cQO5dO0ksin5XXs2pspk75k=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d (sum: h1:/iIZNFGxc/a7C3yWjGcnboV+Tkc7mxr+p6fDztwoxuM=)
```
- The output of 'go version':
`go version go1.15.1 linux/amd64`
- The output of 'go env':
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jacob/.cache/go-build"
GOENV="/home/jacob/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jacob/go/pkg/mod"
GONOPROXY=""GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jacob/.cache/go-build"
GOENV="/home/jacob/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jacob/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jacob/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib64/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-solus-linux-gcc"
CXX="x86_64-solus-linux-g++"
CGO_ENABLED="1"
GOMOD="/home/jacob/Git/fyne/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build004586790=/tmp/go-build -gno-record-gcc-switches"
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jacob/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib64/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="x86_64-solus-linux-gcc"
CXX="x86_64-solus-linux-g++"
CGO_ENABLED="1"
GOMOD="/home/jacob/Git/fyne/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build004586790=/tmp/go-build -gno-record-gcc-switches"
```
- Exactly which command you ran:
`~/Downloads/staticcheck_linux_amd64/staticcheck/staticcheck -f stylish ./...`
Same result with the one downloaded with `go get`.
- Output of the command and what's wrong with the output:
The other failures can be ignored, but this one is a false positive:
```
/home/jacob/Git/fyne/internal/driver/gomobile/device.go
  (16, 2)  U1000  var currentDPI is unused

```
The global variable is actually not unused because it is used in other files inside the same package folder. My guess is that staticcheck thinks that it is unused just because it is never used in that file.

https://github.com/fyne-io/fyne/search?q=currentDPI&unscoped_q=currentDPI

- Where we can read the code you're running staticcheck on:
Develop branch of https://github.com/fyne-io/fyne. I think master would give the same result.

**Comment by dgryski** [comment] 2020-09-12 20:15
I believe this is because the only reads of this global are in files excluded via build tags. (staticcheck is run on Linux but the use is on Android / iOS files).

**Comment by dominikh** [comment] 2020-09-13 23:32
What Damian said. I'll close this as a duplicate of #695 / #48.

**Closed** 2020-09-13 23:32 UTC
Labels: false-positive, needs-triage
