### ISSUE TITLE
feature request: report on useless string conversion in len(string(b))

### ISSUE THREAD

**Issue by randall77** [dominikh/go-tools#1405] opened 2023-05-23 17:32 UTC
See https://go-review.googlesource.com/c/go/+/497276 , in particular the list of places people do `len(string(b))` instead of just `len(b)` (where `b` is a `[]byte`).

**Comment by dominikh** [comment] 2023-05-23 17:46
I could've sworn we already did that, but apparently not.

Closing as a duplicate of #760. I'll try to get around to it soon.

**Closed by dominikh** 2023-05-23 17:46 UTC
Labels: needs-triage
