### ISSUE TITLE
suggest to replace len([]rune(...)) with utf8.RuneCountInString

### ISSUE THREAD

**Issue by martisch** [dominikh/go-tools#748] opened 2020-05-12 08:11 UTC
`len([]rune(...))` is usually less efficient than the utf8 functions and the utf8 functions name seems more descriptive of what it does.

**Comment by dominikh** [comment] 2020-05-12 16:25
Duplicate of #279. It seems that the compiler optimizes this: https://go-review.googlesource.com/c/go/+/108985

**Closed by dominikh** 2020-05-12 16:25 UTC
Labels: needs-triage
