### ISSUE TITLE
honnef.co is down

### ISSUE THREAD

**Issue by peter-edge** [dominikh/go-tools#269] opened 2018-02-28 17:21 UTC
```
$ curl -sSL https://honnef.co/go/tools/cmd/staticcheck?go-get=1
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
```

**Comment by kozlovic** [comment] 2018-02-28 18:08
Running on travis:
```
$ go get -u honnef.co/go/tools/cmd/megacheck
package honnef.co/go/tools/cmd/megacheck: unrecognized import path "honnef.co/go/tools/cmd/megacheck" (parse https://honnef.co/go/tools/cmd/megacheck?go-get=1: no go-import meta tags ())
```

**Comment by dominikh** [comment] 2018-02-28 21:17
It's fixed now. Sorry for the inconvenience.

**Closed by dominikh** 2018-02-28 21:17 UTC

**Comment by CameronAckermanSEL** [comment] 2018-02-28 21:57
We had to remove all go-tool dependencies from our build. Is there a more stable mirror around?

**Comment by robbert229** [comment] 2018-02-28 22:00
I recently had to remove staticcheck from our build because of honnef.co going down. This is also the second time in recent history it has gone down. Is there a more stable way to consume gotools than through honnef.co?

**Comment by dominikh** [comment] 2018-02-28 22:46
in 2017, honnef.co/go had approximately 6 hours of downtime, so about a 99.9% uptime. That's higher than what GitHub managed to achieve in 2017. Of course, honnef.co/go/ still depends on GitHub for the actual `git clone`, which reduces the overall uptime. However, honnef.co/go isn't being the bottleneck here.

Of course, that doesn't really matter, because: you should be aiming for reproducible and reliable builds. Part of that means not depending on external factors. You should be vendoring (or caching, or internally mirroring) your dependencies and tools. Even if neither GitHub nor honnef.co ever went down, the data served could still be broken in various ways, such as a buggy commit on the master branch.

I may, however, consider releasing pre-built binaries on GitHub soon, if there is interest in that.

**Comment by kozlovic** [comment] 2018-02-28 22:52
@dominikh First thank you for your work.. let's not forget that you are doing this on your free time...

I thought about vendoring, but you do some updates quite frequently (adding new checks, etc..) and the nice thing about doing the `got get -u` in travis is that it would always run with the latest checks that you have included. That being said, I could vendor and update from time to time. Things to think about.. Again, thanks for your work!

**Comment by robbert229** [comment] 2018-03-01 00:07
@dominkh BTW don't take my comment as ungratefulness. I really appreciate the wonderful tools you have written that add significant value and catch defects before they leave the door.

**Comment by dominikh** [comment] 2018-03-01 04:55
Thank you for the offer, Peter, but I'll be able to write it myself :)

I've filed https://github.com/dominikh/go-tools/issues/271 to track the progress on it.

**Comment by rajveerappan** [comment] 2018-08-01 17:00
@dominikh this seems to be an issue again right now?

**Comment by barshow** [comment] 2018-08-01 19:14
Have you though about switching the import path to your github, from honnef.co.  Even if it technically has less downtime than github, most workflows stop when github is down, travis builds stop, even some of your tools have github.com imports.  It's also a additional opaque attack vector.

With all that being said, these tools are epic.  Thank you so much for you're work on them!

**Comment by glerchundi** [comment] 2018-08-01 20:45
Same here :(

**Comment by dominikh** [comment] 2018-08-01 21:04
> Have you though about switching the import path to your github, from honnef.co

Only if you consider vendoring your dependencies so issues like these don't impact you ;-)

At any rate, the issue should be fixed now.

Pre-built binaries will land with the next version of staticcheck, which should be in time for Go 1.11.

**Comment by potto007** [comment] 2018-08-01 21:04
Wouldn't you know... right as I finish extracting the files from my previous build images, and refactoring my build, the thing came back up. ;)

**Comment by CameronAckermanSEL** [comment] 2018-08-01 21:10
Vendoring is an acceptable strategy, but if you happen to need to be upgrading some other dependency while any one of the tens of vanity sources are down then tools like `dep` cannot run.

We've vendored our dependencies to help alleviate these problems, and it has, but it's important to acknowledge that this is not a perfect solution.

**Comment by dominikh** [comment] 2018-08-01 21:18
> Vendoring is an acceptable strategy, but if you happen to need to be upgrading some other dependency while any one of the tens of vanity sources are down then tools like dep cannot run.

That sounds like a serious flaw in dep. None of your dependencies should depend on staticcheck, so updating any of those dependencies shouldn't fail because staticcheck fails to update. Updating a dependency shouldn't even attempt to update unrelated packages.

> We are looking forward to when vgo comes out so we can have just one point of failure in these situations.

Ah yes, the coveted [SPOF](https://en.wikipedia.org/wiki/Single_point_of_failure)

**Comment by CameronAckermanSEL** [comment] 2018-08-01 21:27
It's better than 2 SPOFs ;)

**Comment by barshow** [comment] 2018-08-01 21:43
@dominikh vendoring makes sense for application code dependencies.  And can break `dep`ending on how you structure you tests.   Is there a reason not to host from github?

**Comment by dominikh** [comment] 2018-08-01 21:52
> Is there a reason not to host from github?

The major reason for using vanity imports is being able to migrate away from a hosting platform without having to change import paths. C.f. the shutdown of code.google.com.

The major reason for not changing from the current import path to anything else is the large amount of people using the current import paths.

**Comment by matryer** [comment] 2019-11-19 14:45
@dominikh Has this happened again? I'm getting `unrecognized import path \"honnef.co/go/tools\" (https fetch: Get https://honnef.co/go/tools?go-get=1: x509: certificate is valid for *.netlify.com, netlify.com, not honnef.co)` when using `cloud.google.com/go/pubsub`.

**Comment by dmrajkarthick** [comment] 2019-11-19 14:49
@dominikh - I guess it is down again. Getting `unrecognized import path "honnef.co/go/tools"` on my builds.

**Comment by Imelstorm** [comment] 2019-11-19 15:05
Same
unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())

**Comment by mFarghaly** [comment] 2019-11-19 15:06
```
go: honnef.co/go/tools@v0.0.1-2019.2.2: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())
```

**Comment by dominikh** [comment] 2019-11-19 15:15
Please see https://github.com/dominikh/go-tools/issues/658#issuecomment-555551344

**Comment by kaushiknag90** [comment] 2022-05-05 10:58
Seeing this issue again today and getting 502 gateway timeout error whole fetching dependency.

Failure fetching [honnef.co/go/tools](http://honnef.co/go/tools) with 502 gateway timeout error. This is failing in local macbook and multiple Jenkins platforms as well.

Running grpcserver functional tests...
go: github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2 requires
	google.golang.org/genproto@v0.0.0-20200423170343-7949de9c1215 requires
	honnef.co/go/tools@v0.0.0-20190523083050-ea95bdfd59fc: unrecognized import path "honnef.co/go/tools": reading https://honnef.co/go/tools?go-get=1: 502 Bad Gateway
make: *** [grpcserver-functional-test] Error 1
grpc server functional test failed


Can you please help in resolving this as we are blocked due to this.

**Comment by phureerak** [comment] 2022-05-05 11:25
now, i found this error same
go: honnef.co/go/tools@v0.0.0-20190102054323-c2f93a96b099: unrecognized import path "honnef.co/go/tools" (parse https://honnef.co/go/tools?go-get=1: no go-import meta tags ())
