### ISSUE TITLE
staticcheck: SA4006 false-negative when type is number 

### ISSUE THREAD

**Issue by sina-devel** [dominikh/go-tools#1018] opened 2021-05-29 10:22 UTC
<details><summary>staticcheck -version</summary>
<p>

    staticcheck 2021.1 (v0.2.0)

</p>
</details>

<details><summary>staticcheck -debug.version</summary>
<p>

    staticcheck 2021.1 (v0.2.0)

    Compiled with Go version: go1.16.4
    Main module:
        honnef.co/go/tools@v0.2.0 (sum: h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=)
    Dependencies:
        github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
        golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
        golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
        golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
        golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)

</p>
</details>

<details><summary>go version</summary>
<p>

    go version go1.16.4 linux/amd64

</p>
</details>

<details><summary>go env</summary>
<p>

    GO111MODULE="on"
    GOARCH="amd64"
    GOBIN="/home/sina/go/bin"
    GOCACHE="/home/sina/.cache/go-build"
    GOENV="/home/sina/.config/go/env"
    GOEXE=""
    GOFLAGS=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOINSECURE=""
    GOMODCACHE="/home/sina/go/pkg/mod"
    GONOPROXY=""
    GONOSUMDB=""
    GOOS="linux"
    GOPATH="/home/sina/go"
    GOPRIVATE=""
    GOPROXY="https://proxy.golang.org,direct"
    GOROOT="/home/sina/sdk/go1.16.4"
    GOSUMDB="sum.golang.org"
    GOTMPDIR=""
    GOTOOLDIR="/home/sina/sdk/go1.16.4/pkg/tool/linux_amd64"
    GOVCS=""
    GOVERSION="go1.16.4"
    GCCGO="gccgo"
    AR="ar"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="0"
    GOMOD="/home/sina/go/src/sina/example/go.mod"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3572674957=/tmp/go-build -gno-record-gcc-switches"

</p>
</details>

<details><summary>code</summary>
<p>

```go
package main

import (
	"fmt"
)

func main() {
	m := make(map[string]int)
	m["ten"] = 10
	fmt.Println(m["ten"])
	m = make(map[string]int)

	a := 10
	fmt.Println(a)
	a = 5

	b := 10.3
	fmt.Println(b)
	b = 5.7
}


```

</p>
</details>

<details><summary>staticcheck output</summary>
<p>

    main.go:11:2: this value of m is never used (SA4006)

</p>
</details>

I expected it to happen for ‍‍‍`a‍‍‍` and `b`as well

**Comment by dominikh** [comment] 2021-05-29 19:44
Duplicate of https://github.com/dominikh/go-tools/issues/191.

**Closed by dominikh** 2021-05-29 19:44 UTC
Labels: false-negative, needs-triage
