### ISSUE TITLE
No document for U1000 and U1001 in https://staticcheck.io/docs/checks

### ISSUE THREAD

**Issue by haya14busa** [dominikh/go-tools#740] opened 2020-05-10 09:54 UTC
I noticed that U1000 (func funname is unused) is not listed in https://staticcheck.io/docs/checks.

Other rules can be found as https://staticcheck.io/docs/checks#SA9003 for example, but
https://staticcheck.io/docs/checks#U1000 doesn't work.

**Comment by dominikh** [comment] 2020-05-10 10:07
This is on my todo list. I'll close this as a duplicate of https://github.com/dominikh/go-tools/issues/647

**Closed by dominikh** 2020-05-10 10:07 UTC
Labels: needs-triage
