### ISSUE TITLE
detect make slice with length but without cap followed by an append loop

### ISSUE THREAD

**Issue by martisch** [dominikh/go-tools#749] opened 2020-05-12 08:26 UTC
```
bar := make([]int, 8)
for i:= 0; i < 8; i++ {
    bar = append(bar, i)
}
fmt.Println(bar)
```

The author either not inteded to start the slice with alot of zero values and append others or it would be more efficient to have a larger cap. Either way it would be nice to warn about a make without cap but with a length followed by an append loop.

**Comment by dominikh** [comment] 2020-05-12 16:27
Duplicate of #112. It also mentions some of the problems with this idea.

**Closed by dominikh** 2020-05-12 16:27 UTC
Labels: needs-triage
