### ISSUE TITLE
Check for incorrect sort usages

### ISSUE THREAD

**Issue by dsnet** [dominikh/go-tools#763] opened 2020-05-28 18:10 UTC
I'm recently came across code like the following:
```go
ss = sort.StringSlice(ss)
```
The user's intention is to sort `ss`, but they are accidentally just casting `ss` as the [`sort.StringSlice`](https://golang.org/pkg/sort/#StringSlice) type and implicitly storing that back into a `[]string`, which is a noop.

The code the user really wanted was:
```go
sort.Strings(ss)
```

The same problem applies to `sort.Float64Slice` and `sort.IntSlice`.

I saw a small handful of cases like this, but it wasn't a terrible lot. Feel free to close if this isn't deemed common enough.

**Comment by dominikh** [comment] 2020-05-28 18:18
Duplicate of #592, but thanks for reminding me we had that check planned. I'll bump it up the list.

**Closed by dominikh** 2020-05-28 18:18 UTC
Labels: needs-triage
