### ISSUE TITLE
staticcheck: check atomic.Value type consistency

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#1142] opened 2021-12-08 14:19 UTC
https://pkg.go.dev/sync/atomic#Value

 >  A Value provides an atomic load and store of a **consistently typed value.**  […]

(Emphasis added.)

Failure to do so will result in a panic:

```go
package main

import (
	"fmt"
	"sync/atomic"
)

func main() {
	v := &atomic.Value{}
	v.Store(int64(42))
	v.Store(float64(42))
	fmt.Println(v.Load())
}
```

```sh
go run ./main.go
```

```none
panic: sync/atomic: store of inconsistently typed value into Value

goroutine 1 [running]:
sync/atomic.(*Value).Store(0xc00009e210, {0x485520, 0x4b1170})
        /home/ainar/go/go1.17/src/sync/atomic/value.go:77 +0xd8
main.main()
        /home/ainar/dev/tmp/go/tmp/main.go:11 +0x5d
exit status 2
```

**Comment by dominikh** [comment] 2021-12-08 22:25
Closing as a duplicate of https://github.com/dominikh/go-tools/issues/172.

I suspect that this kind of bug will be fixed by using generics, not by using Staticcheck.

**Closed by dominikh** 2021-12-08 22:25 UTC
Labels: needs-triage
