### ISSUE TITLE
type pageRuleConstraint is unused (U1000)

### ISSUE THREAD

**Issue by tlimoncelli** [dominikh/go-tools#1137] opened 2021-11-30 22:00 UTC
- The output of 'staticcheck -version'

```
$ staticcheck -version
staticcheck 2021.1.2 (v0.2.2)
```

- The output of 'staticcheck -debug.version' (it is fine if this command fails)

```
$ staticcheck -debug.version
staticcheck 2021.1.2 (v0.2.2)

Compiled with Go version: go1.17.1
Main module:
	honnef.co/go/tools@v0.2.2 (sum: h1:MNh1AVMyVX23VUHE2O27jm6lNj3vjO5DexS4A1xvnzk=)
Dependencies:
	github.com/BurntSushi/toml@v0.3.1 (sum: h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=)
	golang.org/x/mod@v0.3.0 (sum: h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=)
	golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 (sum: h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=)
	golang.org/x/tools@v0.1.0 (sum: h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=)
	golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 (sum: h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=)
```

- The output of 'go version'

```
$ go version
go version go1.17.3 darwin/amd64
```

- The output of 'go env'

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/tlimoncelli/bin"
GOCACHE="/Users/tlimoncelli/Library/Caches/go-build"
GOENV="/Users/tlimoncelli/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tlimoncelli/go/pkg/mod"
GONOPROXY="github.com/TomOnTime/phpresourcedir/p1extract/scrollodex/reslist"
GONOSUMDB="github.com/TomOnTime/phpresourcedir/p1extract/scrollodex/reslist"
GOOS="darwin"
GOPATH="/Users/tlimoncelli/go"
GOPRIVATE="github.com/TomOnTime/phpresourcedir/p1extract/scrollodex/reslist"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tlimoncelli/git/dnscontrol/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jn/g91v7l7j2_n83kyhh038w7ch0000gq/T/go-build1585882751=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

- Exactly which command you ran

```
$ staticcheck ./...
```

- Output of the command and what's wrong with the output

```
...
providers/cloudflare/rest.go:356:6: type pageRuleConstraint is unused (U1000)
...
```

Type `pageRuleConstraint` is not 

```
$ vi providers/cloudflare/rest.go 
   (Comment out pageRuleConstraint)
$ go test ./...
# github.com/StackExchange/dnscontrol/v3/providers/cloudflare
providers/cloudflare/rest.go:272:32: undefined: pageRuleConstraint
...
```

- Where we can read the code you're running staticcheck on

https://github.com/StackExchange/dnscontrol/blob/master/providers/cloudflare/rest.go

Or, more specifically:

```
$ cd /tmp
$ git clone https://github.com/StackExchange/dnscontrol.git
$ cd dnscontrol 
$ staticcheck ./...
```

(I'm desperately trying to avoid getting on the [long list of competent programmers who got it wrong before](https://staticcheck.io/docs/faq/). At first I thought it was due to the type being defined after use. However swapping it to the start of the file still gets the error. Keeping my fingers crossed!)

**Comment by dominikh** [comment] 2021-12-01 12:16
I believe this is a duplicate of #810 and a bug in Staticcheck. You can [ignore](https://staticcheck.io/docs/configuration/#ignoring-problems) the false positive until we fix it.

You've avoided the list :)

**Closed by dominikh** 2021-12-01 12:16 UTC
Labels: false-positive, needs-triage
