### ISSUE TITLE
nil pointer check doesn't notice an "assert" in a called function

### ISSUE THREAD

**Issue by seebs** [dominikh/go-tools#854] opened 2020-10-19 19:10 UTC
I'm not sure about "code is fine", but code seems like it should be right and I think it is untrue that the pointer can be nil at the point indicated.

```
package scassert

func assert(condition bool) {
	if !condition {
		panic("assertion failed")
	}
}

func DoIt(x *int) {
	assert(x != nil)
	*x = 3
}
```

staticcheck spots the `*x` as a dereference of a possibly-nil pointer. But it's not possibly-nil; if it were nil, the assert call would have paniced.

I'm not happy with the code, but I think the warning might be wrong.

**Comment by dominikh** [comment] 2020-10-19 19:12
Duplicate of #832.

**Closed by dominikh** 2020-10-19 19:12 UTC
Labels: false-positive, needs-triage
