### ISSUE TITLE
panic on go1.18 generic code

### ISSUE THREAD

**Issue by Dreamacro** [dominikh/go-tools#1201] opened 2022-03-16 13:07 UTC
### Version

```shell
❯ staticcheck -version
staticcheck (devel, v0.3.0-0.dev.0.20220306074811-23e1086441d2)
```

```shell
❯ go version                                          
go version go1.18 darwin/arm64
```

### Panic

it panic on generic code

```shell
❯ staticcheck ./...                                   
panic: T

goroutine 285 [running]:
honnef.co/go/tools/go/ir.(*Program).needMethods(0x14007f54000, {0x102ba79e0?, 0x14007f18270?}, 0x0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:237 +0x524
honnef.co/go/tools/go/ir.(*Program).needMethods(0x14007f54000, {0x102ba7968?, 0x14005fb98c0?}, 0x0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:196 +0x2e8
honnef.co/go/tools/go/ir.(*Program).needMethods(0x14007f54000, {0x102ba79b8?, 0x14006fcee70?}, 0x0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:233 +0x600
honnef.co/go/tools/go/ir.(*Program).needMethods(0x14007f54000, {0x102ba7918?, 0x1400618e250?}, 0x0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:182 +0x18c
honnef.co/go/tools/go/ir.(*Program).needMethods(0x14007f54000, {0x102ba78c8?, 0x140075d4930?}, 0x0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:215 +0x4e4
honnef.co/go/tools/go/ir.(*Program).needMethodsOf(0x14006fbc730?, {0x102ba78c8?, 0x140075d4930?})
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/methods.go:145 +0xb4
honnef.co/go/tools/go/ir.(*Package).build(0x14006fb4ab0)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/builder.go:2427 +0xd8
sync.(*Once).doSlow(0x14007f54000?, 0x14007f09630?)
        /Users/dreamacro/sdk/go1.18/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
        /Users/dreamacro/sdk/go1.18/src/sync/once.go:59
honnef.co/go/tools/go/ir.(*Package).Build(...)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/go/ir/builder.go:2415
honnef.co/go/tools/internal/passes/buildir.run(0x14007f21040)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/internal/passes/buildir/buildir.go:86 +0x28c
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0x14007f39f50, {0x102baa1a8?, 0x14006ff0dc0})
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:1032 +0x590
honnef.co/go/tools/lintcmd/runner.genericHandle({0x102baa1a8?, 0x14006ff0dc0}, {0x102baa1a8?, 0x14006ff08c0?}, 0x0?, 0x0, 0x14007f06d78)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:857 +0xd8
honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers(0x14000109a40, 0x14000d9fd40, 0x14007f09680)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:1105 +0x650
honnef.co/go/tools/lintcmd/runner.(*subrunner).doUncached(0x14000109a40, 0x14000d9fd40)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:728 +0x148
honnef.co/go/tools/lintcmd/runner.(*subrunner).do(0x14000109a40, {0x102baa1f0?, 0x14000d9fd40})
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:584 +0x674
honnef.co/go/tools/lintcmd/runner.(*Runner).Run.func2({0x102baa1f0?, 0x14000d9fd40?})
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:1308 +0x38
honnef.co/go/tools/lintcmd/runner.genericHandle({0x102baa1f0?, 0x14000d9fd40}, {0x102baa1f0?, 0x14000d5a240?}, 0x0?, 0x140002d3850, 0x14004005b60)
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:857 +0xd8
created by honnef.co/go/tools/lintcmd/runner.(*Runner).Run
        /Users/dreamacro/go/pkg/mod/honnef.co/go/tools@v0.3.0-0.dev.0.20220306074811-23e1086441d2/lintcmd/runner/runner.go:1307 +0x4dc
```

**Comment by dominikh** [comment] 2022-03-16 13:14
This is a duplicate of #1166.

**Closed by dominikh** 2022-03-16 13:14 UTC
Labels: bug, needs-triage
