### ISSUE TITLE
go1.23rc1: panics when testing with go1.23rc1

### ISSUE THREAD

**Issue by MadhavJivrajani** [dominikh/go-tools#1565] opened 2024-06-24 10:00 UTC
Hi! Thank you for your work maintaining this project <3 

We run tools from this repo via `golangci-lint` in Kubernetes and since go1.23rc1 was recently announced, we kicked off testing with it: https://github.com/kubernetes/kubernetes/pull/125658

As part of that, one of our jobs failed reporting panics that seem to be coming from here. Complete job logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125658/pull-kubernetes-verify-lint/1805126626996916224

This is running `v0.4.6` ([ref](https://github.com/kubernetes/kubernetes/blob/10ae1dbb52d5d03bcbff981065597e341a3d0237/hack/tools/go.mod#L14)). However, please note that I am able to reproduce these failures with `v0.4.7` as well. 

Here's a pretty-printed run-down of all the pancis that I see:
<details>
<summary> 
Panic 1

```
ERROR: level=error msg="[linters_context/goanalysis] buildir: panic during analysis: Cannot range over: func(yield func(E) bool), goroutine 93042 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] buildir: panic during analysis: Cannot range over: func(yield func(E) bool), goroutine 93042 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x1675660?, 0xc018b1ac50?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/go/ir.(*builder).rangeStmt(0xc000071910, 0xc0231c7680, 0xc02236ee40, 0x0, {0x1b1c560, 0xc02236ee40})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2214 +0x894
honnef.co/go/tools/go/ir.(*builder).stmt(0xc000071910, 0xc0231c7680, {0x1b21530?, 0xc02236ee40?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2427 +0x20a
honnef.co/go/tools/go/ir.(*builder).stmtList(...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:847
honnef.co/go/tools/go/ir.(*builder).stmt(0xc000071910, 0xc0231c7680, {0x1b21440?, 0xc01562e8d0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2385 +0x1415
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc000071910, 0xc0231c7680)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2497 +0x417
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0xc000071910, 0xc021dfd320, 0xc01562e900)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2534 +0x189
honnef.co/go/tools/go/ir.(*Package).build(0xc021dfd320)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2638 +0xb46
sync.(*Once).doSlow(0xc021dde540?, 0xc0011ad500?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/sync/once.go:67
honnef.co/go/tools/go/ir.(*Package).Build(...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/go/ir/builder.go:2556
honnef.co/go/tools/internal/passes/buildir.run(0xc01a3fc270)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/internal/passes/buildir/buildir.go:86 +0x18b
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc010b198f0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x1883af5, 0x7}, 0xc019905f48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc004880f00?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc010b198f0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3179
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/go/ir/builder.go#L2214

<details>
<summary> 
Panic 2

```
ERROR: level=error msg="[linters_context/goanalysis] typedness: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92959 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] typedness: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92959 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x171a920?, 0xc01a918b10?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/analysis/facts/typedness.run(0xc01cacc410)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/typedness/typedness.go:59 +0x21d
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc012ab0720)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x18a1906, 0x9}, 0xc016901f48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc004f66a20?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc012ab0720)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3179
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from accessing the map here:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/analysis/facts/typedness/typedness.go#L59

<details>
<summary> 
Panic 3

```
ERROR: level=error msg="[linters_context/goanalysis] SA5012: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92961 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] SA5012: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92961 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x171a920?, 0xc01a8c78f0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/staticcheck.findSliceLenChecks(0xc01e4fd5f0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/staticcheck/lint.go:4285 +0x668
honnef.co/go/tools/staticcheck.CheckEvenSliceLength(0xc01e4fd5f0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/staticcheck/lint.go:4523 +0x18
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc013f72b30)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x18788d5, 0x6}, 0xc020b27748)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc001b2eba0?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc013f72b30)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3179
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from accessing this map here:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/staticcheck/lint.go#L4285

<details>
<summary> 
Panic 4

```
ERROR: level=error msg="[linters_context/goanalysis] nilness: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92956 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] nilness: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92956 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x171a920?, 0xc01a8c7a40?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/analysis/facts/nilness.run(0xc01e4fd930)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/nilness/nilness.go:65 +0x277
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc012ab2d60)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x187ac4e, 0x7}, 0xc00afe9f48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc004880d20?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc012ab2d60)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3179
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from accessing this map here:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/analysis/facts/nilness/nilness.go#L65

<details>
<summary> 
Panic 5

```
ERROR: level=error msg="[linters_context/goanalysis] fact_purity: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92958 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] fact_purity: panic during analysis: interface conversion: interface {} is nil, not *buildir.IR, goroutine 92958 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x171a920?, 0xc01a918f90?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/analysis/facts/purity.purity(0xc01cacc750)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/purity/purity.go:109 +0x299
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc010b1bea0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x18cd922, 0xb}, 0xc00e7f9f48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc004880f60?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc010b1bea0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 3179
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from accessing the map here:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/analysis/facts/purity/purity.go#L109

<details>
<summary> 
Panic 6

```
ERROR: level=error msg="[linters_context/goanalysis] nilness: panic during analysis: internal error: unhandled type *ir.ArrayConst, goroutine 118286 [running]:
```
</summary>
<br>

```
ERROR: level=error msg="[linters_context/goanalysis] nilness: panic during analysis: internal error: unhandled type *ir.ArrayConst, goroutine 118286 [running]:
runtime/debug.Stack()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:104 +0x5a
panic({0x1675660?, 0xc055c314d0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.23rc1.linux-amd64/src/runtime/panic.go:785 +0x132
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x7ff67c2ffa58, 0xc024727aa0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/nilness/nilness.go:239 +0x8a5
honnef.co/go/tools/analysis/facts/nilness.impl.func1({0x1b2d638, 0xc02ab46f00})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/nilness/nilness.go:147 +0x90e
honnef.co/go/tools/analysis/facts/nilness.impl(0xc024c6b2b0, 0xc02727f900, 0xc00bcf5cb8)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/nilness/nilness.go:246 +0x32a
honnef.co/go/tools/analysis/facts/nilness.run(0xc024c6b2b0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/honnef.co/go/tools@v0.4.6/analysis/facts/nilness/nilness.go:66 +0x125
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc012abd500)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:190 +0x9cd
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:112 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0033f4870, {0x187ac4e, 0x7}, 0xc00ba13f48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc00ade8c60?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_action.go:111 +0x6e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc012abd500)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 8397
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/github.com/golangci/golangci-lint@v1.56.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e9
```
</details>

Seems to be coming from:
https://github.com/dominikh/go-tools/blob/f57fec247eddf41c04774af84b91e41dd78a3173/analysis/facts/nilness/nilness.go#L239

Please lmk if I can provide more information, thanks!

**Comment by dominikh** [comment] 2024-06-24 11:21
Panic 1 has already been fixed on master. Panics 2-5 seem like golangci-lint specific panics caused by it insisting to run analyzes that depend on buildir even though buildir has failed. Panic 6 has already been fixed on master.

**Closed by dominikh** 2024-06-24 11:21 UTC
Labels: bug, needs-triage

**Comment by MadhavJivrajani** [comment] 2024-06-26 11:16
Thank you @dominikh, I appreciate the response!
