### ISSUE TITLE
Warning for missing defer.

### ISSUE THREAD

**Issue by c9845** [dominikh/go-tools#1341] opened 2022-12-08 22:10 UTC
When using something like the `sql` package, `defer` statements pretty easy to forget.  Is there a way to lint this and throw a warning?

For example:
```golang
tx, err := c.Begin()
if err != nil {
  panic(err)
}

stmt, err := c.Prepare("INSERT INTO 'table-name' (Fname, Lname) VALUES (?, ?)
if err != nil {
  panic(err)
}
```
There should be a `defer tx.Rollback()` and a defer `stmt.Close()` after the closing curly braces.

This same "forgotten defer" can occur with `os.Open()`, `os.Create()`, `zip.NewWriter()`, mutexes, etc.

**Comment by dominikh** [comment] 2022-12-09 22:01
I'll close this as a duplicate of #150. Generally speaking, this is a hard problem, and not one I'm likely to tackle any time soon.

**Closed by dominikh** 2022-12-09 22:01 UTC
Labels: needs-triage
