### ISSUE TITLE
staticcheck: SA4006 false positive

### ISSUE THREAD

**Issue by ptman** [dominikh/go-tools#709] opened 2020-03-17 08:48 UTC
```
$ staticcheck -version
staticcheck (no version)
$ git describe # in honnef.co/go/tools
2020.1-6-gc702d0a
$ staticcheck -debug.version
staticcheck (no version)

Compiled with Go version: go1.14
Built without Go modules
$ go version
go version go1.14 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build985828270=/tmp/go-build -gno-record-gcc-switches"
```

```
$ staticcheck -checks all ./...
test.go:3:2: this value of nonce is never used (SA4006)
```

```golang
// test.go
func TestGenerateNonce(t *testing.T) {
        nonce, err := generateNonce() // SA4006
        if err != nil {
                t.Error(err)
        }
        if len(nonce) != nonceSize { // used here
                t.Error("nonce length not ok")
        }
}
```

**Comment by ainar-g** [comment] 2020-03-17 10:29
<p>
Can't repro:
</p>

<pre>$ staticcheck --version
staticcheck (devel, v0.0.1-2020.1.0.20200222115104-c702d0a1c8d5)
$ more ./go.tmp_test.go 
package main

import "testing"

func generateNonce() (n []byte, err error) { return nil, nil }

const nonceSize = 0

func TestGenerateNonce(t *testing.T) {
	nonce, err := generateNonce()
	if err != nil {
		t.Error(err)
	}

	if len(nonce) != nonceSize {
		t.Error("nonce length not ok")
	}
}
$ staticcheck --checks=all ./go.tmp_test.go 
$
</pre>

**Comment by ptman** [comment] 2020-03-17 10:51
Well, the file is of course larger and I only included part of it, but the function is copied completely. I have no idea what other factors affect it

**Comment by dominikh** [comment] 2020-03-17 15:36
What's the signature of `generateNonce`? If it returns an array and not a slice, then this is https://github.com/dominikh/go-tools/issues/364 – but it also makes your test unnecessary.

If it's not #364, then I'm afraid I'll need more information, and an actual example that reproduces the problem.

**Comment by ptman** [comment] 2020-03-17 15:56
func generateNonce() (*[nonceSize]byte, error) {

**Comment by dominikh** [comment] 2020-03-17 16:51
Yeah, that's a duplicate of #364 then. But `if len(nonce) != nonceSize {` will never be true, the type system guarantees that. If you want to keep the test, anyway, you'll need to add `//lint:ignore SA4006 false positive` (or some other free-form text after `SA4006`) above the assignment to `nonce` until we fix the bug.

**Closed by dominikh** 2020-03-17 16:51 UTC
Labels: false-positive, waiting-for-feedback

**Comment by ptman** [comment] 2020-03-17 20:22
Thanks for the triage and sorry for the dupe
