### ISSUE TITLE
simple: multiple sequential boolean not operators (!!!!!!!!flag)

### ISSUE THREAD

**Issue by client9** [dominikh/go-tools#88] opened 2017-04-25 18:23 UTC
I bumped into a bug today since I have a double "!!" in a conditional by mistake.

Turns out ` !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!abool` is legit code and not flagged by vet or lint.

I can't think of why "!!" would ever be needed.  (in other languages sometimes it is but not go).   Seems like this could be warned against.

Thoughts?

n

```
package main

import (
	"fmt"
)

func main() {
	hello := true
	fmt.Println(!!!!hello)
}
```

**Comment by shurcooL** [comment] 2017-04-25 20:06
Output of `staticcheck` on your sample above:

```
$ staticcheck
main.go:9:14: negating a boolean twice has no effect; is this a typo? (SA4013)
main.go:9:15: negating a boolean twice has no effect; is this a typo? (SA4013)
main.go:9:16: negating a boolean twice has no effect; is this a typo? (SA4013)
```

**Comment by mvdan** [comment] 2017-04-25 20:43
It's funny that it doesn't stop at the first occurrence within an expression, though.

**Comment by shurcooL** [comment] 2017-04-25 21:26
Yes, but it's worth pointing out it finds distinct issues. The line number is the same, but column is not.

**Comment by client9** [comment] 2017-04-25 21:51
oh I didn't know about staticcheck.  thanks @shurcooL

**Comment by mvdan** [comment] 2017-04-25 22:27
I realise columns are different - but it's still just a chain of the same expressions. Then again, this kind of code is very unlikely to happen . Wasn't mentioning it as a bug to be fixed, really.

**Comment by shurcooL** [comment] 2017-04-25 22:48
> this kind of code is very unlikely to happen

I agree. But see https://github.com/golang/go/issues/5598 and imagine `staticcheck`s output for a laugh. 😆

**Comment by client9** [comment] 2017-04-26 02:14
thanks guys. It's not always clear to me the difference between the linters in this repo.  I'll can just add staticcheck to my gometalinter runs, and problem solved. 💥

**Comment by dominikh** [comment] 2017-05-12 05:27
I will close this issue. The staticcheck check is working as intended (eliminating the "duplicate" errors is not worth the added complexity), and the check wouldn't make much sense in gosimple because it's likely a bug, not just complex code.

@client9 The difference between gosimple and staticcheck is that one tool is anal about writing simpler code, while the other tool points out legitimate issues.

**Closed by dominikh** 2017-05-12 05:27 UTC

**Comment by client9** [comment] 2017-05-12 06:17
thx @dominikh  make sense to me.  thanks for your time.
